import type { ExtractedLabel } from "@/lib/compliance/types";

export type SamplePack = {
  id: string;
  name: string;
  blurb: string;
  image: string;
  injectQr?: string;
  expect: string;
  fallback: ExtractedLabel;
};

const FRESHDROP_QR = JSON.stringify({
  productName: "FreshDrop",
  genericName: "Laundry detergent powder",
  manufacturerName: "Coastal Care Chemicals Pvt Ltd",
  manufacturerAddress: "Plot 12, MIDC Taloja, Navi Mumbai 410208",
  netQuantity: "1 kg",
  mrp: "₹ 210.00 Incl. of all taxes",
  mrpInclusiveOfTaxes: true,
  mfgMonthYear: "JAN 2026",
  consumerCarePhone: "18001234567",
  consumerCareEmail: "care@freshdrop.in",
  countryOfOrigin: "India",
  isImported: false,
});

export const SAMPLE_PACKS: SamplePack[] = [
  {
    id: "nilgiri-gold",
    name: "Nilgiri Gold tea",
    blurb: "Mostly complete food label — a clean pass.",
    image: "/samples/nilgiri-gold.jpg",
    expect: "Should pass the core Legal Metrology checks.",
    fallback: {
      productName: "Nilgiri Gold",
      genericName: "Premium black tea",
      manufacturerName: "Western Ghats Tea Co. Pvt. Ltd.",
      manufacturerAddress: "Coonoor, Tamil Nadu 643101",
      packerName: null,
      importerName: null,
      netQuantity: "250 g",
      mrp: "MRP ₹ 185.00 (Incl. of all taxes)",
      mrpInclusiveOfTaxes: true,
      mfgMonthYear: "JAN 2026",
      packedMonthYear: null,
      bestBefore: "JUL 2027",
      useBy: null,
      consumerCarePhone: "18002024455",
      consumerCareEmail: "care@nilgirigold.in",
      countryOfOrigin: "India",
      isImported: false,
      fssaiLicense: "10024011001234",
      vegNonVeg: "veg",
      unitSalePrice: null,
      barcode: null,
      rawOcrText:
        "NILGIRI GOLD PREMIUM BLACK TEA Net Quantity: 250 g MRP ₹ 185.00 (Incl. of all taxes) Mfg: JAN 2026 Best Before: JUL 2027 Mfd by: Western Ghats Tea Co. Pvt. Ltd., Coonoor, Tamil Nadu 643101 Consumer Care: 1800 202 4455 / care@nilgirigold.in FSSAI 10024011001234",
      category: "food",
    },
  },
  {
    id: "crispy-bites",
    name: "Crispy Bites biscuits",
    blurb: "No MRP on the front — a classic miss.",
    image: "/samples/crispy-bites.jpg",
    expect: "Should fail on MRP and consumer care.",
    fallback: {
      productName: "Crispy Bites",
      genericName: "Glucose biscuits",
      manufacturerName: "Sunbake Foods",
      manufacturerAddress: "Pune",
      packerName: null,
      importerName: null,
      netQuantity: "150 g",
      mrp: null,
      mrpInclusiveOfTaxes: null,
      mfgMonthYear: "MAR 2026",
      packedMonthYear: null,
      bestBefore: "SEP 2026",
      useBy: null,
      consumerCarePhone: null,
      consumerCareEmail: null,
      countryOfOrigin: "India",
      isImported: false,
      fssaiLicense: null,
      vegNonVeg: null,
      unitSalePrice: null,
      barcode: null,
      rawOcrText:
        "Sunbake CRISPY BITES GLUCOSE BISCUITS Net Qty 150 g Mfd: MAR 2026 Best Before: SEP 2026 Sunbake Foods, Pune",
      category: "food",
    },
  },
  {
    id: "masala-munch",
    name: "Masala Munch namkeen",
    blurb: "Price is there; address and care contacts are not.",
    image: "/samples/masala-munch.jpg",
    expect: "Should fail manufacturer address and consumer care.",
    fallback: {
      productName: "Masala Munch",
      genericName: "Spicy mixture",
      manufacturerName: "Munch Co.",
      manufacturerAddress: null,
      packerName: "Munch Co.",
      importerName: null,
      netQuantity: "200 g",
      mrp: "MRP ₹ 55.00 Incl. of all taxes",
      mrpInclusiveOfTaxes: true,
      mfgMonthYear: null,
      packedMonthYear: "FEB 2026",
      bestBefore: null,
      useBy: null,
      consumerCarePhone: null,
      consumerCareEmail: null,
      countryOfOrigin: "India",
      isImported: false,
      fssaiLicense: null,
      vegNonVeg: "veg",
      unitSalePrice: null,
      barcode: null,
      rawOcrText:
        "MASALA MUNCH SPICY MIXTURE Net Quantity 200 g MRP ₹ 55.00 Incl. of all taxes Pkd: FEB 2026 Packed by Munch Co.",
      category: "food",
    },
  },
  {
    id: "freshdrop-qr",
    name: "FreshDrop detergent",
    blurb: "Sparse printed label. QR carries the rest.",
    image: "/samples/freshdrop.jpg",
    injectQr: FRESHDROP_QR,
    expect: "QR-first: printed pack is thin, QR fills mandatory fields.",
    fallback: {
      productName: "FreshDrop",
      genericName: "Laundry detergent",
      manufacturerName: null,
      manufacturerAddress: null,
      packerName: null,
      importerName: null,
      netQuantity: "1 kg",
      mrp: null,
      mrpInclusiveOfTaxes: null,
      mfgMonthYear: null,
      packedMonthYear: null,
      bestBefore: null,
      useBy: null,
      consumerCarePhone: null,
      consumerCareEmail: null,
      countryOfOrigin: null,
      isImported: false,
      fssaiLicense: null,
      vegNonVeg: null,
      unitSalePrice: null,
      barcode: null,
      rawOcrText: "FRESHDROP LAUNDRY DETERGENT Net Qty 1 kg",
      category: "non-food",
    },
  },
  {
    id: "freshdrop-qr-only",
    name: "QR code only",
    blurb: "A real QR payload — no printed declarations.",
    image: "/samples/freshdrop-qr.png",
    expect: "Decoder should read the QR and skip a missing label.",
    fallback: {
      productName: null,
      genericName: null,
      manufacturerName: null,
      manufacturerAddress: null,
      packerName: null,
      importerName: null,
      netQuantity: null,
      mrp: null,
      mrpInclusiveOfTaxes: null,
      mfgMonthYear: null,
      packedMonthYear: null,
      bestBefore: null,
      useBy: null,
      consumerCarePhone: null,
      consumerCareEmail: null,
      countryOfOrigin: null,
      isImported: null,
      fssaiLicense: null,
      vegNonVeg: null,
      unitSalePrice: null,
      barcode: null,
      rawOcrText: "",
      category: "non-food",
    },
  },
];

export function sampleById(id: string | undefined | null) {
  if (!id) return undefined;
  return SAMPLE_PACKS.find((s) => s.id === id);
}
